on: push

name: Jest Suite

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - run: yarn install --ignore-optional --frozen-lockfile --non-interactive --check-files

      # not technically a jest suite, but a build should pass too
      - run: yarn build

      - run: yarn jest:ci
